package ai.drfx.maximus.matrixai.database.repository

import ai.drfx.maximus.matrixai.database.dao.TradingSignalDao
import ai.drfx.maximus.matrixai.database.entities.TradingSignalEntity
import kotlinx.coroutines.flow.Flow
import java.util.UUID

class TradingSignalRepository(
    private val signalDao: TradingSignalDao
) {
    fun getAllSignals(): Flow<List<TradingSignalEntity>> = signalDao.observeAllSignals()

    fun getSignalsByStatus(status: String): Flow<List<TradingSignalEntity>> =
        signalDao.observeSignalsByStatus(status)

    fun getSignalsByAssetClass(assetClass: String): Flow<List<TradingSignalEntity>> =
        signalDao.observeSignalsByAssetClass(assetClass)

    fun getBookmarkedSignals(): Flow<List<TradingSignalEntity>> =
        signalDao.observeBookmarkedSignals()

    fun observeActiveSignalCount(): Flow<Int> = signalDao.observeActiveSignalCount()

    fun observeSignalById(id: String): Flow<TradingSignalEntity?> = signalDao.observeSignalById(id)

    suspend fun getSignalById(id: String): TradingSignalEntity? = signalDao.getSignalById(id)

    suspend fun getSignalCount(): Int = signalDao.getSignalCount()

    suspend fun saveSignal(signal: TradingSignalEntity): Long = signalDao.insertSignal(signal)

    suspend fun saveSignals(signals: List<TradingSignalEntity>): List<Long> =
        signalDao.insertSignals(signals)

    suspend fun updateSignal(signal: TradingSignalEntity): Int = signalDao.updateSignal(signal)

    suspend fun toggleBookmark(id: String, currentVal: Boolean): Int =
        signalDao.updateBookmark(id, !currentVal)

    suspend fun updatePriceAndStatus(id: String, currentPrice: Double, status: String): Int =
        signalDao.updatePriceAndStatus(id, currentPrice, status)

    suspend fun deleteSignal(id: String): Int = signalDao.deleteSignalById(id)

    suspend fun clearSignals(): Int = signalDao.clearAllSignals()

    /**
     * Seeds realistic real-time default trading signals generated by the Maximus AI Quant Engine.
     */
    suspend fun seedDefaultSignalsIfEmpty() {
        if (getSignalCount() == 0) {
            seedDefaultSignals()
        }
    }

    suspend fun seedDefaultSignals() {
        val now = System.currentTimeMillis()
        val defaultSignals = listOf(
            TradingSignalEntity(
                id = "sig_xauusd_buy_01",
                symbol = "XAU/USD",
                assetClass = "Commodities",
                direction = "BUY",
                signalType = "ORDER_BLOCK",
                timeframe = "M15",
                entryPrice = 2862.40,
                stopLoss = 2854.10,
                takeProfit1 = 2874.50,
                takeProfit2 = 2886.00,
                takeProfit3 = 2898.50,
                currentPrice = 2865.80,
                status = "ACTIVE",
                winProbability = 91,
                riskRewardRatio = "1:3.8",
                strategyName = "Maximus Gold H1 Liquidity Sweep & FVG",
                confluenceFactors = "Bullish Order Block retest at $2,862.40, 4H Trendline liquidity swept, RSI 14 Bullish Divergence, High Volume Delta accumulation",
                aiRationale = "Gold swept Asian session lows and rejected cleanly off the H1 institutional mitigation block. Heavy institutional bid flow observed with clean displacement above $2,864.",
                authorAgent = "Maximus Alpha Gold Specialist",
                timestampMs = now - (6 * 60 * 1000),
                isBookmarked = true
            ),
            TradingSignalEntity(
                id = "sig_btcusdt_buy_02",
                symbol = "BTC/USDT",
                assetClass = "Crypto",
                direction = "BUY",
                signalType = "BREAKOUT",
                timeframe = "H1",
                entryPrice = 88450.00,
                stopLoss = 87200.00,
                takeProfit1 = 90200.00,
                takeProfit2 = 91800.00,
                takeProfit3 = 94500.00,
                currentPrice = 88920.00,
                status = "ACTIVE",
                winProbability = 86,
                riskRewardRatio = "1:3.4",
                strategyName = "Maximus BTC Momentum Expansion",
                confluenceFactors = "Break above local consolidation shelf, Funding rate reset neutral, ETF net inflows +$420M, On-chain CVD aggressive market buying",
                aiRationale = "BTC completed an inverse head-and-shoulders neck break on H1 with substantial spot volume. Target liquidity pools resting above $91.5k psych level.",
                authorAgent = "Maximus Crypto Quant Lead",
                timestampMs = now - (22 * 60 * 1000),
                isBookmarked = false
            ),
            TradingSignalEntity(
                id = "sig_eurusd_sell_03",
                symbol = "EUR/USD",
                assetClass = "Forex",
                direction = "SELL",
                signalType = "SCALPING",
                timeframe = "M5",
                entryPrice = 1.04820,
                stopLoss = 1.05010,
                takeProfit1 = 1.04550,
                takeProfit2 = 1.04300,
                takeProfit3 = 1.04100,
                currentPrice = 1.04710,
                status = "TP1_HIT",
                winProbability = 84,
                riskRewardRatio = "1:2.7",
                strategyName = "London Fix Liquidity Grab & Reversal",
                confluenceFactors = "Judas swing into premium 61.8% fib level, Rejection of daily bearish supply zone, ECB dovish commentary overhang",
                aiRationale = "London open pushed price into overhead fair value gap and printed a distinct bear pinbar on M5. TP1 reached at 1.04550 with partial profits locked.",
                authorAgent = "Maximus Forex Intraday Model",
                timestampMs = now - (48 * 60 * 1000),
                isBookmarked = false
            ),
            TradingSignalEntity(
                id = "sig_nvda_buy_04",
                symbol = "NVDA",
                assetClass = "Equities",
                direction = "BUY",
                signalType = "MOMENTUM",
                timeframe = "H1",
                entryPrice = 142.50,
                stopLoss = 138.80,
                takeProfit1 = 148.00,
                takeProfit2 = 153.50,
                takeProfit3 = 160.00,
                currentPrice = 144.10,
                status = "ACTIVE",
                winProbability = 88,
                riskRewardRatio = "1:3.0",
                strategyName = "Blackwell Demand Multiplier",
                confluenceFactors = "Daily volume climax bounce off 20 EMA, Blackwell supply chain guidance raised, Options call volume skew +62%",
                aiRationale = "Institutional accumulation detected on pre-market tape with sustained buyer volume above the $142 pivot. Strong relative strength versus SPY.",
                authorAgent = "Maximus Equities AI",
                timestampMs = now - (75 * 60 * 1000),
                isBookmarked = true
            ),
            TradingSignalEntity(
                id = "sig_nasdaq_sell_05",
                symbol = "NQ / US100",
                assetClass = "Indices",
                direction = "SELL",
                signalType = "INTRADAY",
                timeframe = "M15",
                entryPrice = 21450.00,
                stopLoss = 21560.00,
                takeProfit1 = 21280.00,
                takeProfit2 = 21150.00,
                takeProfit3 = 20980.00,
                currentPrice = 21390.00,
                status = "ACTIVE",
                winProbability = 82,
                riskRewardRatio = "1:2.9",
                strategyName = "New York Session Supply Rejection",
                confluenceFactors = "Equal highs sweep followed by rapid market structure shift (MSS), 10Y Yield tick higher, VIX spike from lows",
                aiRationale = "Morning rally trapped breakout longs at 21,450 before printing strong bearish displacement back below Asian high. High probability downward mean-reversion.",
                authorAgent = "Maximus Indices Desk",
                timestampMs = now - (90 * 60 * 1000),
                isBookmarked = false
            ),
            TradingSignalEntity(
                id = "sig_ethusdt_buy_06",
                symbol = "ETH/USDT",
                assetClass = "Crypto",
                direction = "BUY",
                signalType = "SWING",
                timeframe = "H4",
                entryPrice = 3380.00,
                stopLoss = 3240.00,
                takeProfit1 = 3600.00,
                takeProfit2 = 3850.00,
                takeProfit3 = 4100.00,
                currentPrice = 3610.00,
                status = "TP1_HIT",
                winProbability = 89,
                riskRewardRatio = "1:3.6",
                strategyName = "L2 Gas Expansion & Weekly Accumulation",
                confluenceFactors = "Divergence on weekly Stoch RSI, Layer-2 TVL multi-month peak, Staking queue net zero withdrawals",
                aiRationale = "Multi-week accumulation range resolved upward with breakout candle. TP1 achieved, holding runners for macro expansion towards $3,850.",
                authorAgent = "Maximus Crypto Quant Lead",
                timestampMs = now - (180 * 60 * 1000),
                isBookmarked = true
            ),
            TradingSignalEntity(
                id = "sig_gbpusd_buy_07",
                symbol = "GBP/USD",
                assetClass = "Forex",
                direction = "BUY",
                signalType = "SCALPING",
                timeframe = "M5",
                entryPrice = 1.26400,
                stopLoss = 1.26180,
                takeProfit1 = 1.26800,
                takeProfit2 = 1.27200,
                takeProfit3 = null,
                currentPrice = 1.26480,
                status = "ACTIVE",
                winProbability = 79,
                riskRewardRatio = "1:2.5",
                strategyName = "Cable London Open Range Break",
                confluenceFactors = "Bounce off key 1.2640 support line, UK Services PMI beat expectations, USD DXY index rejecting resistance at 106.80",
                aiRationale = "Clear double bottom on M5 with bullish confirmation candle closing over the 50 SMA. Risk defined tightly below swing low.",
                authorAgent = "Maximus Forex Intraday Model",
                timestampMs = now - (15 * 60 * 1000),
                isBookmarked = false
            ),
            TradingSignalEntity(
                id = "sig_solusdt_buy_08",
                symbol = "SOL/USDT",
                assetClass = "Crypto",
                direction = "BUY",
                signalType = "SCALPING",
                timeframe = "M15",
                entryPrice = 194.20,
                stopLoss = 189.50,
                takeProfit1 = 202.00,
                takeProfit2 = 210.00,
                takeProfit3 = 225.00,
                currentPrice = 202.40,
                status = "TP1_HIT",
                winProbability = 85,
                riskRewardRatio = "1:3.3",
                strategyName = "DEX Volume Surge & Liquidity Expansion",
                confluenceFactors = "DEX 24h volume surpasses $4.2B, Clean flip of resistance into support at $194, 1-hour bull pennant resolved",
                aiRationale = "Strong follow-through on breakout with aggressive bid wall absorbing all pullbacks. Partial profit taken at $202.",
                authorAgent = "Maximus Crypto Quant Lead",
                timestampMs = now - (110 * 60 * 1000),
                isBookmarked = false
            )
        )
        saveSignals(defaultSignals)
    }
}
